### ISSUE TITLE
PIC12 Bootloader

### ISSUE THREAD

**Issue by amcgee** [WellDone/MoMo-Firmware#14]

**Comment by timburke** [comment]
First working version of the pic12 bootloader in feature-pic12bootloader branch.  Commit is:
a6be18406df742a7e900d75524577990d987b030

Application code is loaded in the high ~1000 words of memory.  The bootloader still takes up a lot of space (1240 words currently) but that's due in large part to stupidity on the part of xc8.  Future work should be able to streamline it down significantly by reimplementing key parts in assembly.

There's now a skeleton example of a mib application module for pic12 that can be loaded by the bootloader in mib12_sdk.  The bootloader has been renamed mib12_executive in recognition of its working status.

Outstanding TODOS are:
- [ ] Add function table to mib12_executive with api that application code can call
- [x] Test to make sure mib slave endpoints are properly passed to application code
- [ ] Slim down mib12_executive by reimplementing key functions in assembly
- [ ] Add module registration logic to mib12_executive (get a slave address from controller before passing control to application)
- [ ]Make application modules define a self-description structure and use it to call the mib registration function from the controller
- [ ] Add watchdog timer on application code with a timeout of 1 sec so that we don't brick if the application sucks.  Upon reset from watchdog timeout, delay a certain amount of time (say 5 sec) before re-entering application code so that we have a chance to bootload a new firmware image.  Pull the alarm pin low so that we know when the reset has occurred and we can tell the device to bootload

**Comment by timburke** [comment]
MIB12 Executive now seems reasonably stable and works well, apart from the outstanding TODOs listed above.  Beginning to use it to develop other module code.

**Comment by amcgee** [comment]
I think this is stable enough to close this issue, Tim would you do the honors?

**Comment by timburke** [comment]
Pic12 bootloader now works.  It can bootload over i2c as well as provides an executive kernel that handles all MIB related communication.  Further pic12 bootloader enhancements will be tracked in a separate issue.
